version: "3.2"
services:
  cypress:
    image: cypress/included:7.2.0
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    entrypoint: []
    command: bash -c 'npx wait-on http://novnc:8080 && cypress open-ct --project /e2e'
    working_dir: /e2e
    volumes:
      - ./:/e2e
  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
      - RUN_XTERM=no
    ports:
      - "8080:8080"
